name: AI Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  review:
    uses: wenjuin95/AI-code-review/.github/workflows/review.yml@master

    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
